import { Router } from 'express';
import healthRoutes from './health.routes.js';
import authRoutes from '../modules/auth.routes.js';
import profileRoutes from '../modules/profile.routes.js';
import preferenceRoutes from '../modules/preferences.routes.js';
import resumeRoutes from '../modules/resumes.routes.js';
import connectionRoutes from '../modules/connections.routes.js';
import jobRoutes from '../modules/jobs.routes.js';
import applicationRoutes from '../modules/applications.routes.js';
import outreachRoutes from '../modules/outreach.routes.js';
import notificationRoutes from '../modules/notifications.routes.js';
import dashboardRoutes from '../modules/dashboard.routes.js';
import noteRoutes from '../modules/notes.routes.js';
import integrationsRoutes from '../modules/integrations.routes.js';
import telegramRoutes from '../modules/telegram.routes.js';
import incomingJobRoutes from '../modules/incoming-jobs.routes.js';
import aiRoutes from '../modules/ai.routes.js';
import outreachAiRoutes from '../modules/outreach-ai.routes.js';
import searchRoutes from '../modules/search.routes.js';
import adminQueueRoutes from '../modules/admin-queue.routes.js';
import modelRegistryRoutes from '../modules/model-registry.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/profile', profileRoutes);
router.use('/preferences', preferenceRoutes);
router.use('/resumes', resumeRoutes);
router.use('/connections', connectionRoutes);
router.use('/jobs', jobRoutes);
router.use('/applications', applicationRoutes);
router.use('/outreach', outreachRoutes);
router.use('/outreach/ai-drafts', outreachAiRoutes);
router.use('/notifications', notificationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/notes', noteRoutes);
router.use('/integrations', integrationsRoutes);
router.use('/integrations/telegram', telegramRoutes);
router.use('/incoming-jobs', incomingJobRoutes);
router.use('/ai', aiRoutes);
router.use('/search', searchRoutes);
router.use('/admin/ai-queue', adminQueueRoutes);
router.use('/admin/models', modelRegistryRoutes);

export default router;
