import dotenv from 'dotenv';
import Joi from 'joi';

const isTest = process.env.NODE_ENV === 'test' || process.argv.some(arg => arg.includes('jest'));

if (isTest) {
  process.env.NODE_ENV = 'test';
  dotenv.config({ path: '.env.test' });
} else {
  dotenv.config();
}

const schema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().integer().min(1).max(65535).default(5000),
  DATABASE_DIALECT: Joi.string().valid('postgres', 'sqlite').default('postgres'),
  DATABASE_URL: Joi.alternatives().conditional('DATABASE_DIALECT', {
    is: 'postgres',
    then: Joi.string().uri({ scheme: ['postgres', 'postgresql'] }).required(),
    otherwise: Joi.string().allow('', null).optional(),
  }),
  DATABASE_STORAGE: Joi.alternatives().conditional('DATABASE_DIALECT', {
    is: 'sqlite',
    then: Joi.string().required(),
    otherwise: Joi.string().allow('', null).optional(),
  }),
  CORS_ORIGIN: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  ACCESS_TOKEN_TTL_MINUTES: Joi.number().integer().min(1).default(10080),
  REFRESH_TOKEN_TTL_DAYS: Joi.number().integer().min(1).default(30),
  RESUME_STORAGE_PATH: Joi.string().default('./storage/resumes'),
  AUTH_RATE_LIMIT_WINDOW_MINUTES: Joi.number().integer().min(1).default(15),
  AUTH_RATE_LIMIT_MAX_REQUESTS: Joi.number().integer().min(1).default(50),
  ADZUNA_APP_ID: Joi.string().allow('', null).default(''),
  ADZUNA_APP_KEY: Joi.string().allow('', null).default(''),
  ADZUNA_COUNTRY: Joi.string().default('in'),
  ADZUNA_ENABLED: Joi.boolean().default(false),
  GMAIL_ENABLED: Joi.boolean().default(false),
  GOOGLE_CLIENT_ID: Joi.string().allow('', null).optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().allow('', null).optional(),
  GOOGLE_REDIRECT_URI: Joi.string().uri().allow('', null).optional(),
  GMAIL_OAUTH_SCOPES: Joi.string().default(
    'https://www.googleapis.com/auth/gmail.readonly'
  ),
  GMAIL_JOB_LABEL: Joi.string().default('CareerGraph/LinkedInJobs'),
  TELEGRAM_ENABLED: Joi.boolean().default(false),
  TELEGRAM_BOT_TOKEN: Joi.string().allow('', null).default(''),
  TELEGRAM_MODE: Joi.string().valid('polling', 'webhook').default('polling'),
  TELEGRAM_BOT_USERNAME: Joi.string().default('CareerGraphJobBot'),
  AI_ENABLED: Joi.boolean().default(false),
  AI_PROVIDER: Joi.string().valid('mock', 'ollama', 'groq').default('mock'),
  AI_JOB_ENRICHMENT_ENABLED: Joi.boolean().default(true),
  AI_RESUME_ENABLED: Joi.boolean().default(true),
  AI_CONNECTION_ENABLED: Joi.boolean().default(true),
  AI_OUTREACH_ENABLED: Joi.boolean().default(true),
  SEMANTIC_SEARCH_ENABLED: Joi.boolean().default(true),
  GROQ_API_KEY: Joi.string().allow('', null).optional(),
  GROQ_MODEL: Joi.string().default('openai/gpt-oss-120b'),
  OLLAMA_BASE_URL: Joi.string().uri().default('http://localhost:11434'),
  OLLAMA_MODEL: Joi.string().default('gemma2:2b'),
  OLLAMA_EMBEDDING_MODEL: Joi.string().default('qwen2.5-coder:7b'),
  AI_TIMEOUT_MS: Joi.number().integer().default(300000),
  AI_MAX_RETRIES: Joi.number().integer().default(2),
  AI_RESUME_PROMPT_CHAR_BUDGET_GROQ: Joi.number().integer().min(0).default(6000),
  AI_RESUME_PROMPT_CHAR_BUDGET_OLLAMA: Joi.number().integer().min(0).default(20000),
  AI_RESUME_PROMPT_CHAR_BUDGET_MOCK: Joi.number().integer().min(0).default(0),
  SMTP_HOST: Joi.string().allow('', null).default(''),
  SMTP_PORT: Joi.number().integer().default(587),
  SMTP_USER: Joi.string().allow('', null).default(''),
  SMTP_PASS: Joi.string().allow('', null).default(''),
  SMTP_FROM: Joi.string().default('CareerGraph AI <noreply@example.com>'),
  REDIS_ENABLED: Joi.boolean().default(false),
  REDIS_URL: Joi.string().uri({ scheme: ['redis', 'rediss'] }).allow('', null).default('redis://localhost:6379'),
  AI_QUEUE_DRIVER: Joi.string().valid('memory', 'redis').default('memory'),
  AI_WORKER_CONCURRENCY: Joi.number().integer().min(1).default(1),
  AI_JOB_ATTEMPTS: Joi.number().integer().min(1).default(3),
  AI_JOB_BACKOFF_MS: Joi.number().integer().min(0).default(5000),
  AI_JOB_REMOVE_ON_COMPLETE: Joi.number().integer().min(0).default(1000),
  AI_JOB_REMOVE_ON_FAIL: Joi.number().integer().min(0).default(5000),
  AI_QUEUE_RATE_LIMIT_MAX: Joi.number().integer().min(1).default(10),
  AI_QUEUE_RATE_LIMIT_DURATION: Joi.number().integer().min(1).default(60000),
  AI_OPERATOR_EMAILS: Joi.string().default('satardekaraary@gmail.com'),
  AI_WORKER_SHUTDOWN_TIMEOUT_MS: Joi.number().integer().min(0).default(30000),
  AI_WORKER_HEARTBEAT_INTERVAL_MS: Joi.number().integer().min(100).default(10000),
  AI_WORKER_ID: Joi.string().allow('', null).optional(),
  ML_SERVICE_ENABLED: Joi.boolean().default(false),
  ML_SERVICE_URL: Joi.string().uri().default('http://localhost:8000'),
  ML_SERVICE_TIMEOUT_MS: Joi.number().integer().min(1).default(5000),
  ML_SERVICE_EMBEDDING_MODEL: Joi.string().default('all-MiniLM-L6-v2'),
  AI_WORKER_EMBEDDED: Joi.boolean().default(false),
  OPPORTUNITY_RANKER_SHADOW_ENABLED: Joi.boolean().default(false),
  MODEL_REGISTRY_ENABLED: Joi.boolean().default(false),
  MODEL_REGISTRY_DEFAULT_ENVIRONMENT: Joi.string().valid('development', 'staging', 'production').default('development'),
  MLFLOW_ENABLED: Joi.boolean().default(false),
}).unknown(true);

const { error, value } = schema.validate(process.env, { abortEarly: false });

if (error) {
  throw new Error(`Invalid environment configuration: ${error.message}`);
}

export const env = {
  nodeEnv: value.NODE_ENV,
  port: value.PORT,
  databaseDialect: value.DATABASE_DIALECT,
  databaseUrl: value.DATABASE_URL,
  databaseStorage: value.DATABASE_STORAGE,
  corsOrigin: value.CORS_ORIGIN,
  jwtAccessSecret: value.JWT_ACCESS_SECRET,
  jwtRefreshSecret: value.JWT_REFRESH_SECRET,
  accessTokenTtlMinutes: value.ACCESS_TOKEN_TTL_MINUTES,
  refreshTokenTtlDays: value.REFRESH_TOKEN_TTL_DAYS,
  resumeStoragePath: value.RESUME_STORAGE_PATH,
  authRateLimitWindowMinutes: value.AUTH_RATE_LIMIT_WINDOW_MINUTES,
  authRateLimitMaxRequests: value.AUTH_RATE_LIMIT_MAX_REQUESTS,
  adzunaAppId: value.ADZUNA_APP_ID,
  adzunaAppKey: value.ADZUNA_APP_KEY,
  adzunaCountry: value.ADZUNA_COUNTRY,
  adzunaEnabled: value.ADZUNA_ENABLED,
  gmailEnabled: value.GMAIL_ENABLED,
  googleClientId: value.GOOGLE_CLIENT_ID,
  googleClientSecret: value.GOOGLE_CLIENT_SECRET,
  googleRedirectUri: value.GOOGLE_REDIRECT_URI,
  gmailOauthScopes: value.GMAIL_OAUTH_SCOPES,
  gmailJobLabel: value.GMAIL_JOB_LABEL,
  telegramEnabled: value.TELEGRAM_ENABLED,
  telegramBotToken: value.TELEGRAM_BOT_TOKEN,
  telegramMode: value.TELEGRAM_MODE,
  telegramBotUsername: value.TELEGRAM_BOT_USERNAME,
  aiEnabled: value.AI_ENABLED,
  aiProvider: value.AI_PROVIDER,
  aiJobEnrichmentEnabled: value.AI_JOB_ENRICHMENT_ENABLED,
  aiResumeEnabled: value.AI_RESUME_ENABLED,
  aiConnectionEnabled: value.AI_CONNECTION_ENABLED,
  aiOutreachEnabled: value.AI_OUTREACH_ENABLED,
  semanticSearchEnabled: value.SEMANTIC_SEARCH_ENABLED,
  groqApiKey: value.GROQ_API_KEY,
  groqModel: value.GROQ_MODEL,
  ollamaBaseUrl: value.OLLAMA_BASE_URL,
  ollamaModel: value.OLLAMA_MODEL,
  ollamaEmbeddingModel: value.OLLAMA_EMBEDDING_MODEL,
  aiTimeoutMs: value.AI_TIMEOUT_MS,
  aiMaxRetries: value.AI_MAX_RETRIES,
  aiResumePromptCharBudgetGroq: value.AI_RESUME_PROMPT_CHAR_BUDGET_GROQ,
  aiResumePromptCharBudgetOllama: value.AI_RESUME_PROMPT_CHAR_BUDGET_OLLAMA,
  aiResumePromptCharBudgetMock: value.AI_RESUME_PROMPT_CHAR_BUDGET_MOCK,
  smtpHost: value.SMTP_HOST,
  smtpPort: value.SMTP_PORT,
  smtpUser: value.SMTP_USER,
  smtpPass: value.SMTP_PASS,
  smtpFrom: value.SMTP_FROM,
  redisEnabled: value.REDIS_ENABLED,
  redisUrl: value.REDIS_URL,
  aiQueueDriver: value.AI_QUEUE_DRIVER,
  aiWorkerConcurrency: value.AI_WORKER_CONCURRENCY,
  aiJobAttempts: value.AI_JOB_ATTEMPTS,
  aiJobBackoffMs: value.AI_JOB_BACKOFF_MS,
  aiJobRemoveOnComplete: value.AI_JOB_REMOVE_ON_COMPLETE,
  aiJobRemoveOnFail: value.AI_JOB_REMOVE_ON_FAIL,
  aiQueueRateLimitMax: value.AI_QUEUE_RATE_LIMIT_MAX,
  aiQueueRateLimitDuration: value.AI_QUEUE_RATE_LIMIT_DURATION,
  aiOperatorEmails: value.AI_OPERATOR_EMAILS,
  aiWorkerShutdownTimeoutMs: value.AI_WORKER_SHUTDOWN_TIMEOUT_MS,
  aiWorkerHeartbeatIntervalMs: value.AI_WORKER_HEARTBEAT_INTERVAL_MS,
  aiWorkerId: value.AI_WORKER_ID,
  mlServiceEnabled: value.ML_SERVICE_ENABLED,
  mlServiceUrl: value.ML_SERVICE_URL,
  mlServiceTimeoutMs: value.ML_SERVICE_TIMEOUT_MS,
  mlServiceEmbeddingModel: value.ML_SERVICE_EMBEDDING_MODEL,
  aiWorkerEmbedded: value.AI_WORKER_EMBEDDED,
  modelRegistryEnabled: value.MODEL_REGISTRY_ENABLED,
  modelRegistryDefaultEnvironment: value.MODEL_REGISTRY_DEFAULT_ENVIRONMENT,
  mlflowEnabled: value.MLFLOW_ENABLED,
  opportunityRankerShadowEnabled: value.OPPORTUNITY_RANKER_SHADOW_ENABLED,
};
